name: Testing Ruby CI
on: [pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: test
          
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
    - name: Install protoc-gen-go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Verify DB connection
      env:
        PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
        done
    - name: Run Ruby tests
      run: |
        gem install bundler
        bundle install
        make test
      env:
        DB_USER: test
        DB_PASS: password
        DB_HOST: 127.0.0.1
        DB_NAME: test
        DB_PORT: 3306
        ECDSA_KEY: You can use the main.go inside cmd/generate-ecdsa-private-key to generate this
        KEY_CLAIM_TOKEN: TokenUsedToVerifyClaimRequest
        RETRIEVE_HMAC_KEY: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        METRICS_USERNAME: 1234567890
        METRICS_PASSWORD: 1234567890
